### ISSUE TITLE
Missing Required File

### ISSUE THREAD

**Issue by nimrodbusany** [RiccardoDeMasellis/FLLOAT#12]
The following link from the readme.md is broken:

https://www.dropbox.com/s/pffn9tl53rd8dzx/MainInterface.java?dl=0

**Comment by RiccardoDeMasellis** [comment]
Hello,
sorry for that, the link should now work. (The class is anyway only a client class for the main methods for the automata construction, which are in Main.java.)

Cheers,

Riccardo
